config/routes.rb
Rails.application.routes.draw do
  
  scope "/:locale" do
	  root "home#index"
	  
	  resources :books
	  
	  resources :users
	  get 'email', to: 'users#by_email', as: :email

	  resources :borrow, only: [:new, :create]
	  get 'return/book' , to: 'borrow#return_book', as: :return
	  post 'return', to: 'borrow#destroy', as: :borrow_destroy
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	has_many :borrows

	before_save { self.title = title.downcase }

	validates :title, :author, presence: true
	validates :title, uniqueness: { case_sensitive: false }
	validates_inclusion_of :state_machine, :in => %w( available unavailable )
	validates :quantity, numericality: {greater_than_or_equal_to: 0}
	validates :quantity, numericality: {less_than_or_equal_to: :quantity_total}
  	validates :quantity_total, numericality: { greater_than_or_equal_to: :quantity}
  	validate :check_quantity

  	def check_quantity
  		if self.quantity_total != self.quantity + self.borrows.length
  			errors.add(:quantity, "Book quantity invalid.")
  		end
  	end

  	def self.stats
  		_stats = ActiveRecord::Base.connection.execute("select sum(quantity), sum(quantity_total) from books;").values.first
	  	stats = {available: _stats[0], unavailable: _stats[1] - _stats[0], total: _stats[1]}
	end

	def switch_state_machine
		if self.quantity == 0 && self.available?
			self.state_machine = "unavailable"
		elsif self.quantity != 0 && !self.available?
			self.state_machine = "available"
		end
	end

	def increase_quantity
		self.quantity = self.quantity + 1
	end

	def decrease_quantity
		self.quantity = self.quantity - 1
	end

	def can_be_returned?
		self.quantity < self.quantity_total
	end

	def available?
		self.state_machine == "available"
	end
end

app/models/borrow.rb
class Borrow < ApplicationRecord

	delegate :email, to: :user, prefix: true, allow_nil: true
	delegate :title, to: :book, prefix: true, allow_nil: true
	belongs_to :user
	belongs_to :book

	validates_uniqueness_of :user_id, :scope => :book_id

end

app/models/user.rb
class User < ApplicationRecord
	
	has_many :borrows

	mount_uploader :photo, PhotoUploader

	before_save { self.email = email.downcase }

	validates :first_name, :last_name, :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }
	validates_inclusion_of :state_machine, :in => %w( not_borrower borrower )

	def self.stats
		_stats = User.all.group(:state_machine).count
  		borrowers = _stats['borrower'] || 0
  		not_borrowers = _stats['not_borrower'] || 0
	  	stats = {borrower: borrowers, not_borrower: not_borrowers, total: borrowers + not_borrowers}
	end

	def switch_state_machine
		if self.borrows.length == 0 && self.state_machine == 'borrower'
			self.state_machine = 'not_borrower'
		elsif self.borrows.length != 0 && self.state_machine == 'not_borrower'
			self.state_machine = "borrower"
		end
	end

	def borrower?
		self.state_machine == "borrower"
	end

	def get_books
      books = Array.new
      if self.borrows.length > 0
        self.borrows.each do |borrow|
          books.push({title: borrow.book.title})
        end
      else
        books.push({title: I18n.t('borrow.new.json.books')})
      end
      books
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :set_locale

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
	end

	def default_url_options
		{ locale: I18n.locale }
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.order(:title).where("title like ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @books.map{ |book| {:label => book.title} }}
    end
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.switch_state_machine
    @book.save
  end

  def update
    @book.update(book_params)
    temp_state_machine = @book.state_machine
    @book.switch_state_machine
    if @book.state_machine != temp_state_machine
      @book.save
    end
  end

  def destroy
    if !@book.can_be_returned?
      @book.destroy
      @check = true
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :summary, :state_machine, :user, :quantity, :quantity_total)
  end
  
end

app/controllers/borrow_controller.rb
class BorrowController < ApplicationController
	before_action :init_error, except: [:new, :return_book], if: :error?
	before_action :set_user, only: [:destroy, :create]
	before_action :set_book, only: [:destroy, :create]

	def new
		@button_name = t('borrow_book.submit')
		@url = borrow_index_path
		@borrow = Borrow.new
	end

	def return_book
		@button_name = t('return_book.submit')
		@url = borrow_destroy_path
		@borrow = Borrow.new
		render 'new'
	end

	def create
		if @error.length == 0
			if @book.available?
				@borrow = Borrow.new(book: @book, user: @user)
				if @borrow.save
					@user.switch_state_machine
					@user.save
					@book.decrease_quantity
					@book.switch_state_machine
					@book.save
				else
					@error.push(t('controller.borrow.user_has_book'))
				end
			else
				@error.push(t('controller.borrow.book_unavailable'))
			end	
		end
	end

	def destroy
		if @error.length == 0
			if @book.can_be_returned?
				if set_borrow
					if @borrow.destroy
						@user.switch_state_machine
						@user.save
						@book.increase_quantity
						@book.switch_state_machine
						@book.save
					end
				end
			else
				@error.push(t('controller.borrow.book_available'))
			end
		end
	end

	private

	def error?
		if !@error
			true
		else
			false
		end
	end
	
	def set_user
		@user = User.find_by(:email => params[:borrow][:user_email])
		if @user == nil
			@error.push(t('controller.borrow.invalid_user'))
		end
	end

	def set_book
		@book = Book.find_by(:title => params[:borrow][:book_title])
		if @book == nil
			@error.push(t('controller.borrow.invalid_book'))
		end
	end

	def init_error
		if !@error
			@error = Array.new
		end
	end

	def set_borrow
		@borrow = Borrow.find_by(book: @book, user: @user)
		if @borrow
			true
		else
			@error.push(t('controller.borrow.user_has_not_book'))
			false
		end
	end

	def borrow_params
		params.require(:borrow).permit(:user_id, :book_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		book_stats = Book.stats
		@nb_books_available = book_stats[:available]
		@nb_books_unavailable = book_stats[:unavailable]
		@nb_books = book_stats[:total]
		user_stats = User.stats
		@nb_users_borrower = user_stats[:borrower]
		@nb_users_not_borrower = user_stats[:not_borrower]
		@nb_users = user_stats[:total]
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email).where("email like ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @users.map{ |user| {:label => user.email} }}
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
  end

  def update
    @user.update(user_params)
  end

  def destroy
    if !@user.borrower?
      @user.destroy
      @check = true
    end
  end

  def by_email
     user = User.find_by_email(params[:email])
     if user
       books = user.get_books
     else 
       user = t('borrow.new.json.users')
     end
     result = {user: user, books: books}
     render json: result
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:last_name, :first_name, :email, :photo, :state_machine)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrow_helper.rb
module BorrowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_row.html.erb
<tr id="book_<%= book.id %>">
	<td><%= book.title %></td>
	<td><%= book.author %></td>
	<td><%= book.summary %></td>
	<td><%= t('books_partial.' + book.state_machine) %></td>
	<td><%= book.quantity %> / <%= book.quantity_total %></td>
	<td><% if book.borrows.length > 0 %>
		<ul><% book.borrows.each do |borrow| %>
			<li><%= link_to (borrow.user.first_name + ' ' + borrow.user.last_name), user_path(borrow.user) %></li>
		<% end %></ul>
	<% else %>
		<%= t('books_partial.user') %>
	<% end %></td>
	<td><%= link_to t('books_partial.show'), book %> | 
	    <%= link_to t('books_partial.edit'), edit_book_path(book), remote: true %> | 
	    <%= link_to t('books_partial.delete'), book, method: :delete, data: { confirm: t('books_partial.confirm') }, :remote => true %></td>
</tr>

app/views/books/_form.html.erb
<div id="book-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= t('form_book.' + params[:action]) %> <%= t('form_book.model') %></h4>
      </div>
      <%= form_for @book, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label t('form_book.title') %>
          <%= f.text_field :title, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label t('form_book.author') %>
          <%= f.text_field :author, class: "form-control" %>
        </div>

        <div class="form-group" style="resize:none;">
          <%= f.label t('form_book.summary') %>
          <%= f.text_area :summary, class: "form-control", rows: 5, id: "comment" %>
        </div>

        <div class="form-group">
          <%= f.label t('form_book.quantity') %>
          <%= f.number_field :quantity, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label t('form_book.quantity_total') %>
          <%= f.number_field :quantity_total, class: "form-control" %>
        </div>
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('form_book.close') %></button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/create.js.erb
<% if @book.errors.blank? %>
  $('#notice').text("");
  $('#book-modal').modal('hide');
  $('table tbody').append('<%= j render "book_row", book: @book %>');
<% else %>
  $('#notice').text("");
  $('.modal-header').append('<ul><% @book.errors.full_messages.each do |error| %><li><%= "#{error}" %></li><% end %></ul>');
<% end %>

app/views/books/destroy.js.erb
<% if !@check %>
	alert('<%= t("books_partial.not_destroy", :book => @book.title)%>');
<% else %>
  alert('<%= t("books_partial.destroy", :book => @book.title)%>');
  $("#book_<%=@book.id%>").remove();
<% end %>

app/views/books/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('books.title') %></h1>

<%= link_to t('books.new'), new_book_path, remote: true, class: "btn btn-primary" %>

<table class="table">
    <tr>
      <th><%= t('books.book_title') %></th>
      <th><%= t('books.author') %></th>
      <th><%= t('books.summary') %></th>
      <th><%= t('books.state_machine') %></th>
      <th><%= t('books.quantity') %></th>
      <th><%= t('books.users') %></th>
      <th><%= t('books.actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <%= render 'book_row', book: book %>
    <% end %>
  </tbody>
</table>

<%= link_to t('books.new'), new_book_path, remote: true, class: "btn btn-primary" %>

app/views/books/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-4">
    <div class="card">
        <div class="card-block">
            <h2 class="card-title mt-3"><%= @book.title %></h2>
            <hr>
            <ul>
            	<li><%= @book.author %></li>
            	<li><%= t('book.' + @book.state_machine) %></li>
            	<li><%= t('book.quantity') %><%= @book.quantity %> / <%= @book.quantity_total %></li>
            </ul>
            <% if @book.borrows.length > 0 %>
            	<hr>
            	<p><%= t('book.users') %></p>
        		<ul>
		  	  		<% @book.borrows.each do |borrow| %>
			  			<li><%= link_to (borrow.user.first_name + ' ' + borrow.user.last_name), user_path(borrow.user) %></li>
			  		<% end %>
        		</ul>
        	<% end %>
            <hr>
            <div class="card-text">
                <%= @book.summary %>
            </div>
        </div>
        <div class="card-footer">
            <small><%= t('book.update') %><%= I18n.localize @book.updated_at, format: :date %></small></br>
            <%= link_to t('book.back'), books_path %>
        </div>
    </div>
</div>

app/views/books/update.js.erb
<% if @book.errors.blank? %>
  $('#notice').text("");
  $('#book-modal').modal('hide');
  $("#book_<%=@book.id%>").replaceWith('<%= j render "book_row", book: @book %>');
<% else %>
  $('#notice').text("");
  $('.modal-header').append('<ul><% @book.errors.full_messages.each do |error| %><li><%= "#{error}" %></li><% end %></ul>');
<% end %>

app/views/borrow/_form_borrow.html.erb
<div class="container">
  <%= form_for @borrow, :url => @url, :html => { :multipart => true }, remote: :true do |f| %>
    <div class="form-group">
      <%= f.label t('form_borrow.user') %><br>
      <%= f.text_field :user_email, data: { autocomplete_source: users_path }, class: "form-control", id: "user_email" %>
    </div>

    <div class="form-group">
      <%= f.label t('form_borrow.book') %><br>
      <%= f.text_field :book_title, data: { autocomplete_source: books_path }, class: "form-control", id: "book_title" %>
    </div>

    <div class="form-group">
      <%= f.submit @button_name, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/borrow/create.js.erb
<% if @borrow && @borrow.errors.blank? %>
  $('#notice').text("");
  $('#book_title').val("");
  $('#notice').append('<%=  t("controller.borrow.borrow", :book => @book.title, :first_name=> @user.first_name, :last_name =>@user.last_name)%>');
<% else %>
  $('#notice').text("");
  $('#notice').append('<ul><% @error.each do |error| %><li><%= error %></li><% end %></ul>');
<% end %>

app/views/borrow/destroy.js.erb
<% if @borrow.present? %>
  $('#notice').text("");
  $('#book_title').val("");
  $('#notice').append('<%=  t("controller.borrow.return", :book => @book.title, :first_name=> @user.first_name, :last_name =>@user.last_name)%>');
<% else %>
  $('#notice').text("");
  $('#notice').append('<ul><% @error.each do |error| %><li><%= error %></li><% end %></ul>');
<% end %>

app/views/borrow/new.html.erb
<p id="notice"></p>

<div id="container">
	<div id="form">
		<%= render "form_borrow" %>
	</div>
	<div id="preview">
        <div class="card-block">
            <h2 class="card-title mt-3" id="name"><%= t('borrow.new.utilisateur') %></h2>
            <hr>
            <ul id="books">
            </ul>
        </div>
	</div>
</div>

app/views/home/index.html.erb
<h1><%= t('home.title')%></h1>

<table class="table">
	<thead>
		<tr>
			<th><%= t('home.nb_books')%></th>
			<th><%= t('home.nb_books_available')%></th>
			<th><%= t('home.nb_books_borrowed')%></th>
			<th><%= t('home.nb_users')%></th>
			<th><%= t('home.nb_users_with_book')%></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @nb_books %></td>
			<td><%= @nb_books_available %></td>
			<td><%= @nb_books_unavailable %></td>
			<td><%= @nb_users %></td>
			<td><%= @nb_users_borrower %></td>
		</tr>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PriumTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'partials/navBar' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_navBar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%= t('nav_bar.name') %></a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to t('nav_bar.home'), root_path %></li>
      <li><%= link_to t('nav_bar.users'), users_path %></li>
      <li><%= link_to t('nav_bar.books'), books_path %></li>
      <li><%= link_to t('nav_bar.borrow'), new_borrow_path %></li>
      <li><%= link_to t('nav_bar.return'), return_path %></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('nav_bar.language') %><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to_unless I18n.locale == :en, t('nav_bar.en'), locale: :en %></li>
          <li><%= link_to_unless I18n.locale == :fr, t('nav_bar.fr'), locale: :fr %></li>
        </ul>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<div id="user-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= t('form_user.' + params[:action]) %> <%= t('form_user.model') %></h4>
      </div>
      <%= form_for @user, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label t('form_user.first_name') %>
          <%= f.text_field :first_name, class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label t('form_user.last_name') %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label t('form_user.email') %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label t('form_user.photo') %>
          <%= f.file_field :photo, class: "btn btn-default" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('form_user.close') %></button>
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user_row.html.erb
<tr id="user_<%= user.id %>">
	<td><% if user.photo.present? %>
		<%= image_tag user.photo.url(:small_thumb) %>
	<% else %>
		<%= t('users_partial.photo') %>
	<% end %></td>
	<td><%= user.first_name %></td>
	<td><%= user.last_name %></td>
	<td><%= user.email %></td>
	<td><%= t('users_partial.' + user.state_machine) %></td>
	<td><% if user.borrows.length > 0 %>
	  	<ul>
			<% user.borrows.each do |borrow| %>
				<li><%= link_to borrow.book.title, book_path(borrow.book) %></li>
			<% end %>
		</ul>
	<% else %>
		<%= t('users_partial.book') %>
	<% end %></td>
	<td><%= link_to t('users_partial.show'), user %> | 
	    <%= link_to t('users_partial.edit'), edit_user_path(user), remote: true %> | 
	    <%= link_to t('users_partial.delete'), user, method: :delete, data: { confirm: t('users_partial.confirm') }, :remote => true %></td>
</tr>

app/views/users/create.js.erb
<% if @user.errors.blank? %>
  $('#notice').text("");
  $('#user-modal').modal('hide');
  $('table tbody').append('<%= j render "user_row", user: @user %>');
<% else %>
  $('#notice').text("");
  $('.modal-header').append('<ul><% @user.errors.full_messages.each do |error| %><li><%= "#{error}" %></li><% end %></ul>');
<% end %>

app/views/users/destroy.js.erb
<% if !@check %>
  alert('<%= t("users_partial.not_destroy", :first_name => @user.first_name, :last_name => @user.last_name)%>');
<% else %>
  alert('<%= t("users_partial.destroy", :first_name => @user.first_name, :last_name => @user.last_name)%>');
  $("#user_<%=@user.id%>").remove();
<% end %>

app/views/users/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('users.title') %></h1>

<%= link_to t('users.new'), new_user_path, remote: true, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th><%= t('users.photo') %></th>
      <th><%= t('users.last_name') %></th>
      <th><%= t('users.first_name') %></th>
      <th><%= t('users.email') %></th>
      <th><%= t('users.state_machine') %></th>
      <th><%= t('users.books') %></th>
      <th><%= t('users.actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <%= render 'user_row', user: user %>
    <% end %>
  </tbody>
</table>

<%= link_to t('users.new'), new_user_path, remote: true, class: "btn btn-primary" %>

app/views/users/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-4">
    <div class="card">
        <div class="card-block">
            <h2 class="card-title mt-3"><%= @user.last_name %> <%= @user.first_name %></h2>
            <p><%= @user.email %></p>
            <p><%= t('user.' + @user.state_machine) %></p>
            <hr>
            <p><%= t('user.books') %></p>
            <ul>
            	<% if @user.borrows.length > 0 %>
					<% @user.borrows.each do |borrow| %>
						<li><%= link_to borrow.book.title, book_path(borrow.book) %></li>
					<% end %>
			  	<% else %>
					<li><%= t('user.book') %></li>
			  	<% end %>
            </ul>
            <hr>
            <div class="card-text">
              <% if @user.photo.present? %>
				<%= image_tag @user.photo.url(:small_thumb) %>
			  <% else %>
				<%= t('user.photo') %>
			  <% end %>
            </div>
        </div>
        <div class="card-footer">
            <small><%= t('user.update') %><%= I18n.localize @user.updated_at, format: :date %></small></br>
            <%= link_to t('user.back'), users_path %>
        </div>
    </div>
</div>

app/views/users/update.js.erb
<% if @user.errors.blank? %>
  $('#notice').text("");
  $('#user-modal').modal('hide');
  $("#user_<%=@user.id%>").replaceWith('<%= j render "user_row", user: @user %>');
<% else %>
  $('#notice').text("");
  $('.modal-header').append('<ul><% @user.errors.full_messages.each do |error| %><li><%= "#{error}" %></li><% end %></ul>');
<% end %>